ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Hang-2016-10-06//RUFIPOGON/chr06_joint_genotyping_rufipogon.vcf.gz_BIALLELIC_SNPs.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Hang-2016-10-06//RUFIPOGON/chr11_joint_genotyping_rufipogon.vcf.gz_BIALLELIC_SNPs.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Hang-2016-10-06//RUFIPOGON/chr12_joint_genotyping_rufipogon.vcf.gz_BIALLELIC_SNPs.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Hang-2016-10-06//RUFIPOGON/chr03_joint_genotyping_rufipogon.vcf.gz_BIALLELIC_SNPs.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Hang-2016-10-06//RUFIPOGON/chr04_joint_genotyping_rufipogon.vcf.gz_BIALLELIC_SNPs.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Hang-2016-10-06//RUFIPOGON/chr01_joint_genotyping_rufipogon.vcf.gz_BIALLELIC_SNPs.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Hang-2016-10-06//RUFIPOGON/chr08_joint_genotyping_rufipogon.vcf.gz_BIALLELIC_SNPs.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Hang-2016-10-06//RUFIPOGON/chr07_joint_genotyping_rufipogon.vcf.gz_BIALLELIC_SNPs.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Hang-2016-10-06//RUFIPOGON/chr02_joint_genotyping_rufipogon.vcf.gz_BIALLELIC_SNPs.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Hang-2016-10-06//RUFIPOGON/chr10_joint_genotyping_rufipogon.vcf.gz_BIALLELIC_SNPs.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Hang-2016-10-06//RUFIPOGON/chr05_joint_genotyping_rufipogon.vcf.gz_BIALLELIC_SNPs.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Hang-2016-10-06//RUFIPOGON/chr09_joint_genotyping_rufipogon.vcf.gz_BIALLELIC_SNPs.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Hang-2016-10-06//JAPONICA/POST/chr11_joint_genotyping_japonica.vcf.gz_BIALLELIC_SNPs.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Hang-2016-10-06//JAPONICA/POST/chr08_joint_genotyping_japonica.vcf.gz_BIALLELIC_SNPs.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Hang-2016-10-06//JAPONICA/POST/chr04_joint_genotyping_japonica.vcf.gz_BIALLELIC_SNPs.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Hang-2016-10-06//JAPONICA/POST/chr01_joint_genotyping_japonica.vcf.gz_BIALLELIC_SNPs.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Hang-2016-10-06//JAPONICA/POST/chr06_joint_genotyping_japonica.vcf.gz_BIALLELIC_SNPs.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Hang-2016-10-06//JAPONICA/POST/chr05_joint_genotyping_japonica.vcf.gz_BIALLELIC_SNPs.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Hang-2016-10-06//JAPONICA/POST/chr02_joint_genotyping_japonica.vcf.gz_BIALLELIC_SNPs.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Hang-2016-10-06//JAPONICA/POST/chr10_joint_genotyping_japonica.vcf.gz_BIALLELIC_SNPs.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Hang-2016-10-06//JAPONICA/POST/chr09_joint_genotyping_japonica.vcf.gz_BIALLELIC_SNPs.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Hang-2016-10-06//JAPONICA/POST/chr03_joint_genotyping_japonica.vcf.gz_BIALLELIC_SNPs.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Hang-2016-10-06//JAPONICA/POST/chr12_joint_genotyping_japonica.vcf.gz_BIALLELIC_SNPs.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Hang-2016-10-06//JAPONICA/POST/chr07_joint_genotyping_japonica.vcf.gz_BIALLELIC_SNPs.vcf.gz .
