ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/100_samples_from_genome.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/200_samples_from_genome.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/300_samples_from_genome.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_1001_1100.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_101_200.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_1101_1200.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_1201_1300.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_1301_1400.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_1401_1500.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_1501_1600.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_1601_1700.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_1701_1800.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_1801_1900.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_1901_2000.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_1_100.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_2001_2100.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_201_300.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_2101_2200.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_2201_2300.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_2301_2424.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_301_400.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_401_500.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_501_600.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_601_700.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_701_800.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_77.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_801_900.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_901_1000.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_bu_168.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/461_101_200.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/461_1_100.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/461_201_300.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/461_301_400.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/461_401_461.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/462_101_200.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/462_1_100.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/462_201_300.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/462_301_400.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/462_401_462.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/50.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/533_101_200.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/533_1_100.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/533_201_300.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/533_301_400.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/533_401_533.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/620_101_200.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/620_1_100.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/620_201_300.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/620_301_400.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/620_401_620.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/ERP000235_output_raw_snps_indels.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/ERP000236_output_raw_snps_indels.g.vcf.gz .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/100_samples_from_genome.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/200_samples_from_genome.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/300_samples_from_genome.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_1001_1100.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_101_200.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_1101_1200.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_1201_1300.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_1301_1400.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_1401_1500.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_1501_1600.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_1601_1700.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_1701_1800.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_1801_1900.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_1901_2000.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_1_100.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_2001_2100.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_201_300.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_2101_2200.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_2201_2300.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_2301_2424.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_301_400.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_401_500.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_501_600.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_601_700.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_701_800.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_77.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_801_900.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_901_1000.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/3K_bu_168.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/461_101_200.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/461_1_100.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/461_201_300.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/461_301_400.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/461_401_461.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/462_101_200.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/462_1_100.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/462_201_300.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/462_301_400.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/462_401_462.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/50.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/533_101_200.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/533_1_100.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/533_201_300.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/533_301_400.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/533_401_533.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/620_101_200.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/620_1_100.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/620_201_300.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/620_301_400.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/620_401_620.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/ERP000235_output_raw_snps_indels.g.vcf.gz.tbi .
ln -s /lustre1/deng_pkuhpc/slh_RICE_data/Genotyping_GVCFs/LAST/ERP000236_output_raw_snps_indels.g.vcf.gz.tbi .
